
export interface Template {
  id: string;
  name: string;
  thumbnailUrl: string;
  category: string;
  toolType: 'Invoice' | 'Estimate' | 'Quote' | 'Insurance';
  description: string;
  useCases: string[];
  isPro?: boolean;
}

export const allTemplates: Template[] = [
  // --- INVOICE TEMPLATES ---
  {
    id: 'default',
    name: 'Classic',
    thumbnailUrl: '/templates/Default.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A timeless and universally professional design suitable for any business. Clear, concise, and easy to read.',
    useCases: ['Any Business', 'Startups', 'Consultants'],
  },
  {
    id: 'modern',
    name: 'Modern',
    thumbnailUrl: '/templates/Modern.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A clean, contemporary design with a strong visual hierarchy. Perfect for tech companies and creative agencies.',
    useCases: ['Tech', 'Creative Agencies', 'Marketing'],
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    thumbnailUrl: '/templates/Minimalist.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A simple, elegant layout that focuses on the essentials. Ideal for freelancers and designers who value clarity.',
    useCases: ['Freelancers', 'Designers', 'Minimalists'],
  },
  {
    id: 'creative',
    name: 'Creative',
    thumbnailUrl: '/templates/Creative.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A stylish template with a unique layout and color accents, designed to make your brand stand out.',
    useCases: ['Artists', 'Photographers', 'Boutiques'],
  },
  {
    id: 'elegant',
    name: 'Elegant',
    thumbnailUrl: '/templates/Elegant.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A sophisticated design with a touch of class, perfect for high-end services and luxury goods.',
    useCases: ['Consultants', 'Luxury Brands', 'High-End Services'],
  },
  {
    id: 'usa',
    name: 'USA',
    thumbnailUrl: '/templates/Usa.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A professional and compliant template designed specifically for US-based businesses.',
    useCases: ['US Businesses', 'Contractors', 'Service Providers'],
  },
  {
    id: 'construction-1',
    name: 'Foundation',
    thumbnailUrl: '/templates/invoicepagetemplates/Foundation.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A detailed and professional template for construction projects, outlining labor and materials separately.',
    useCases: ['General Contractors', 'Builders', 'Renovators'],
  },
   {
    id: 'construction-2',
    name: 'Modern Dark',
    thumbnailUrl: '/templates/invoicepagetemplates/Moderndark.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A sleek, dark-themed template for construction companies wanting a modern and bold look.',
    useCases: ['Modern Builders', 'Design-Build Firms', 'Architects'],
  },
  {
    id: 'construction-3',
    name: 'Minimalist',
    thumbnailUrl: '/templates/invoicepagetemplates/Minimalist.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A clean and minimal design that focuses on the core details of the construction job.',
    useCases: ['Subcontractors', 'Small Firms', 'Renovators'],
  },
  {
    id: 'construction-4',
    name: 'Side Accent',
    thumbnailUrl: '/templates/invoicepagetemplates/SideAccent.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'Features a colored side panel for a touch of branding while keeping the main content area clean.',
    useCases: ['General Contractors', 'Commercial Construction'],
  },
  {
    id: 'plumbing-1',
    name: 'Direct Flow',
    thumbnailUrl: '/templates/invoicepagetemplates/Direct-Flow.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A straightforward template for plumbing jobs, clearly listing services and costs.',
    useCases: ['Residential Plumbing', 'Emergency Repairs'],
  },
  {
    id: 'electrical-1',
    name: 'Voltage',
    thumbnailUrl: '/templates/invoicepagetemplates/Voltage.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A sharp, professional template for electricians and electrical contractors.',
    useCases: ['Electricians', 'Wiring Services'],
  },
  {
    id: 'hvac-1',
    name: 'Climate Control',
    thumbnailUrl: '/templates/invoicepagetemplates/Climate-Control.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A clean and detailed template perfect for HVAC installation and repair services.',
    useCases: ['HVAC Technicians', 'Heating & Cooling'],
  },
  {
    id: 'roofing-1',
    name: 'Top View',
    thumbnailUrl: '/templates/invoicepagetemplates/Top-View.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'A comprehensive template for roofing estimates and invoices.',
    useCases: ['Roofers', 'Exterior Contractors'],
  },
  {
    id: 'landscaping-1',
    name: 'Green Thumb',
    thumbnailUrl: '/templates/invoicepagetemplates/Green-Thumb.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'A nature-inspired template perfect for landscaping and lawn care businesses.',
    useCases: ['Landscapers', 'Gardeners', 'Arborists'],
  },
  {
    id: 'cleaning-1',
    name: 'Sparkle',
    thumbnailUrl: '/templates/invoicepagetemplates/Sparkle.png',
    category: 'Cleaning Services',
    toolType: 'Invoice',
    description: 'A bright and clean template for residential and commercial cleaning services.',
    useCases: ['Maid Services', 'Janitorial', 'Carpet Cleaning'],
  },
  {
    id: 'auto-repair-1',
    name: 'Mechanic',
    thumbnailUrl: '/templates/invoicepagetemplates/Mechanic.png',
    category: 'Auto Repair',
    toolType: 'Invoice',
    description: 'A practical and detailed template for auto repair shops and mechanics.',
    useCases: ['Auto Shops', 'Body Work', 'Mechanics'],
  },
  {
    id: 'it-1',
    name: 'Tech Corporate',
    thumbnailUrl: '/templates/invoicepagetemplates/Tech-Corporate.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A professional and modern template designed for IT services and tech support businesses.',
    useCases: ['IT Support', 'Tech Services', 'Managed Services'],
  },
  {
    id: 'freelance-1',
    name: 'Modern Freelancer',
    thumbnailUrl: '/templates/invoicepagetemplates/Modern-Freelancer.png',
    category: 'Freelance / Agency',
    toolType: 'Invoice',
    description: 'A stylish and clean invoice perfect for freelancers, creatives, and small agencies.',
    useCases: ['Freelancers', 'Designers', 'Consultants'],
  },
  {
    id: 'consulting-1',
    name: 'Expert',
    thumbnailUrl: '/templates/invoicepagetemplates/Expert.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A sharp, professional invoice for consultants and advisors.',
    useCases: ['Business Consultants', 'Financial Advisors'],
  },
  {
    id: 'legal-1',
    name: 'Gavel',
    thumbnailUrl: '/templates/invoicepagetemplates/Gavel.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'A formal and classic invoice template suitable for law firms and legal professionals.',
    useCases: ['Lawyers', 'Paralegals', 'Legal Advisors'],
  },
  {
    id: 'medical-1',
    name: 'Caduceus',
    thumbnailUrl: '/templates/invoicepagetemplates/Caduceus.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A clean and professional template for medical billing and healthcare services.',
    useCases: ['Clinics', 'Doctors', 'Medical Billing'],
  },
  {
    id: 'ecommerce-1',
    name: 'Shopify',
    thumbnailUrl: '/templates/invoicepagetemplates/Shopify.png',
    category: 'E-commerce / Online Store',
    toolType: 'Invoice',
    description: 'A modern and item-focused invoice for e-commerce and online sales.',
    useCases: ['Online Stores', 'E-commerce', 'Dropshippers'],
  },
  {
    id: 'retail-1',
    name: 'Receipt',
    thumbnailUrl: '/templates/invoicepagetemplates/Receipt.png',
    category: 'Retail / Wholesale',
    toolType: 'Invoice',
    description: 'A clear, receipt-style invoice for retail sales and wholesale orders.',
    useCases: ['Retail Stores', 'Wholesalers'],
  },
  {
    id: 'photography-1',
    name: 'Lens',
    thumbnailUrl: '/templates/invoicepagetemplates/Lens.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'An elegant template with a focus on visual branding for photographers.',
    useCases: ['Photographers', 'Videographers'],
  },
  {
    id: 'real-estate-1',
    name: 'Property',
    thumbnailUrl: '/templates/invoicepagetemplates/Property.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'A professional template for real estate transactions and property management fees.',
    useCases: ['Realtors', 'Property Managers'],
  },
  {
    id: 'transportation-1',
    name: 'Freight',
    thumbnailUrl: '/templates/invoicepagetemplates/Freight.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A clear and detailed invoice for transportation and logistics companies.',
    useCases: ['Logistics', 'Freight', 'Trucking'],
  },
  {
    id: 'rental-1',
    name: 'Lease',
    thumbnailUrl: '/templates/invoicepagetemplates/Lease.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A simple invoice for rental properties and equipment.',
    useCases: ['Landlords', 'Equipment Rental'],
  },


  // --- ESTIMATE & QUOTE TEMPLATES ---
  {
    id: 'generic-1',
    name: 'Classic Estimate',
    thumbnailUrl: '/templates/generic-1.png',
    category: 'Generic',
    toolType: 'Estimate',
    description: 'A timeless and professional estimate layout suitable for any industry. Clear, organized, and easy for clients to understand.',
    useCases: ['Any Business', 'General Quotes', 'Proposals'],
  },
  {
    id: 'generic-2',
    name: 'Modern Estimate',
    thumbnailUrl: '/templates/generic-2.png',
    category: 'Generic',
    toolType: 'Estimate',
    description: 'A sleek, contemporary design that puts your brand front and center. Ideal for modern businesses and creative professionals.',
    useCases: ['Agencies', 'Tech Startups', 'Consultants'],
  },
   {
    id: 'generic-1',
    name: 'Classic Quote',
    thumbnailUrl: '/templates/generic-1.png',
    category: 'Generic',
    toolType: 'Quote',
    description: 'A timeless and professional quote layout suitable for any industry. Clear, organized, and easy for clients to understand.',
    useCases: ['Any Business', 'General Quotes', 'Proposals'],
  },
  {
    id: 'generic-2',
    name: 'Modern Quote',
    thumbnailUrl: '/templates/generic-2.png',
    category: 'Generic',
    toolType: 'Quote',
    description: 'A sleek, contemporary design that puts your brand front and center. Ideal for modern businesses and creative professionals.',
    useCases: ['Agencies', 'Tech Startups', 'Consultants'],
  },
   {
    id: 'construction-1-est',
    name: 'Foundation Estimate',
    thumbnailUrl: '/templates/construction-1.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A detailed estimate template for construction work.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-2-est',
    name: 'Modern Dark Estimate',
    thumbnailUrl: '/templates/construction-2.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A dark, modern estimate for construction projects.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-3-est',
    name: 'Minimalist Estimate',
    thumbnailUrl: '/templates/construction-3.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A clean, minimal estimate for construction services.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-4-est',
    name: 'Side Accent Estimate',
    thumbnailUrl: '/templates/construction-4.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A construction estimate with a colored side accent panel.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-5-est',
    name: 'Bold Grid Estimate',
    thumbnailUrl: '/templates/construction-5.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A grid-based layout for clear construction estimates.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
 
  // --- INSURANCE TEMPLATES ---
  {
    id: 'usa-claim-default',
    name: 'USA Claim Form',
    thumbnailUrl: '/templates/Usa-insurance.png',
    category: 'Claims',
    toolType: 'Insurance',
    description: 'A standard, comprehensive claim form template suitable for various insurance types in the USA.',
    useCases: ['Claims Processing', 'Damage Reports', 'Vehicle Insurance'],
  },
  {
    id: 'usa-service',
    name: 'USA Service',
    thumbnailUrl: '/templates/Usa-service.png',
    category: 'Policy',
    toolType: 'Insurance',
    description: 'A professional template for outlining insurance policy details, coverage, and terms for US-based clients.',
    useCases: ['Policy Issuance', 'Coverage Summary', 'Certificates'],
  },
];
