
export interface Template {
  id: string;
  name: string;
  thumbnailUrl: string;
  category: string;
  toolType: 'Invoice' | 'Estimate' | 'Quote' | 'Insurance';
  description: string;
  useCases: string[];
  isPro?: boolean;
}

export const allTemplates: Template[] = [
  // --- INVOICE TEMPLATES ---
  {
    id: 'default',
    name: 'Classic',
    thumbnailUrl: '/templates/Default.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A timeless and universally professional design suitable for any business. Clear, concise, and easy to read.',
    useCases: ['Any Business', 'Startups', 'Consultants'],
  },
  {
    id: 'modern',
    name: 'Modern',
    thumbnailUrl: '/templates/Modern.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A clean, contemporary design with a strong visual hierarchy. Perfect for tech companies and creative agencies.',
    useCases: ['Tech', 'Creative Agencies', 'Marketing'],
  },
  {
    id: 'minimalist',
    name: 'Minimalist',
    thumbnailUrl: '/templates/Minimalist.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A simple, elegant layout that focuses on the essentials. Ideal for freelancers and designers who value clarity.',
    useCases: ['Freelancers', 'Designers', 'Minimalists'],
  },
  {
    id: 'creative',
    name: 'Creative',
    thumbnailUrl: '/templates/Creative.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A stylish template with a unique layout and color accents, designed to make your brand stand out.',
    useCases: ['Artists', 'Photographers', 'Boutiques'],
  },
  {
    id: 'elegant',
    name: 'Elegant',
    thumbnailUrl: '/templates/Elegant.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A sophisticated design with a touch of class, perfect for high-end services and luxury goods.',
    useCases: ['Consultants', 'Luxury Brands', 'High-End Services'],
  },
  {
    id: 'usa',
    name: 'USA',
    thumbnailUrl: '/templates/Usa.png',
    category: 'General Services',
    toolType: 'Invoice',
    description: 'A professional and compliant template designed specifically for US-based businesses.',
    useCases: ['US Businesses', 'Contractors', 'Service Providers'],
  },
  // --- Construction Invoice Templates ---
  {
    id: 'construction-1',
    name: 'Foundation',
    thumbnailUrl: '/templates/invoicepagetemplates/FoundationInvoicetemplate.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A detailed and professional template for construction projects, outlining labor and materials separately.',
    useCases: ['General Contractors', 'Builders', 'Renovators'],
  },
  {
    id: 'construction-2',
    name: 'Modern Dark',
    thumbnailUrl: '/templates/invoicepagetemplates/Moderndark.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A sleek, dark-themed template for construction companies wanting a modern and bold look.',
    useCases: ['Modern Builders', 'Design-Build Firms', 'Architects'],
  },
  {
    id: 'construction-3',
    name: 'Minimalist',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanMinimal.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A clean and minimal design that focuses on the core details of the construction job.',
    useCases: ['Subcontractors', 'Small Firms', 'Renovators'],
  },
  {
    id: 'construction-4',
    name: 'Side Accent',
    thumbnailUrl: '/templates/invoicepagetemplates/SideAccent.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'Features a colored side panel for a touch of branding while keeping the main content area clean.',
    useCases: ['General Contractors', 'Commercial Construction'],
  },
  {
    id: 'construction-5',
    name: 'Bold Grid',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanGrid.png',
    category: 'Construction',
    toolType: 'Invoice',
    description: 'A grid-based layout for clear construction invoices.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  // --- Plumbing Invoice Templates ---
  {
    id: 'plumbing-1',
    name: 'Direct Flow',
    thumbnailUrl: '/templates/invoicepagetemplates/DirectFlow.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A straightforward template for plumbing jobs, clearly listing services and costs.',
    useCases: ['Residential Plumbing', 'Emergency Repairs'],
  },
  {
    id: 'plumbing-2',
    name: 'Modern Blue',
    thumbnailUrl: '/templates/invoicepagetemplates/ModernBlue.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A clean, modern template with blue accents, ideal for professional plumbing services.',
    useCases: ['Plumbing Companies', 'Service Calls'],
  },
  {
    id: 'plumbing-3',
    name: 'Clean & Minimal',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanMinimal.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A simple and elegant template that is easy to read and focuses on the essentials.',
    useCases: ['Independent Plumbers', 'Small Jobs'],
  },
  {
    id: 'plumbing-4',
    name: 'Side panel',
    thumbnailUrl: '/templates/invoicepagetemplates/Sidepanel.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A stylish template with a side panel for company branding and contact information.',
    useCases: ['Commercial Plumbing', 'Contracts'],
  },
  {
    id: 'plumbing-5',
    name: 'Bold Grid Plumbing',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanGrid.png',
    category: 'Plumbing',
    toolType: 'Invoice',
    description: 'A bold, grid-based layout for clear and organized billing.',
    useCases: ['New Construction', 'Large Projects'],
  },
  // --- Electrical Invoice Templates ---
  {
    id: 'electrical-1',
    name: 'Voltage',
    thumbnailUrl: '/templates/invoicepagetemplates/Voltage.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A sharp, professional template for electricians and electrical contractors.',
    useCases: ['Electricians', 'Wiring Services'],
  },
  {
    id: 'electrical-2',
    name: 'Circuit',
    thumbnailUrl: '/templates/invoicepagetemplates/Circuit.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A modern template with circuit-themed design elements for tech-savvy electricians.',
    useCases: ['Commercial Electricians', 'Smart Home Installers'],
  },
  {
    id: 'electrical-3',
    name: 'Spark',
    thumbnailUrl: '/templates/invoicepagetemplates/Spark.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A clean and minimalist template for quick and clear electrical service billing.',
    useCases: ['Residential Electricians', 'Repair Services'],
  },
  {
    id: 'electrical-4',
    name: 'Wired',
    thumbnailUrl: '/templates/invoicepagetemplates/Wired.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A stylish invoice with a side panel accent, great for professional branding.',
    useCases: ['Electrical Contractors', 'Project Bids'],
  },
  {
    id: 'electrical-5',
    name: 'Power Grid',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanGrid.png',
    category: 'Electrical Services',
    toolType: 'Invoice',
    description: 'A bold, grid-based layout for detailed and organized electrical invoices.',
    useCases: ['Industrial Electrical', 'Large-scale Projects'],
  },
  // --- HVAC Invoice Templates ---
  {
    id: 'hvac-1',
    name: 'Clean Grid',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanGrid.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A clean and detailed template perfect for HVAC installation and repair services.',
    useCases: ['HVAC Technicians', 'Heating & Cooling'],
  },
  {
    id: 'hvac-2',
    name: 'Climate Control',
    thumbnailUrl: '/templates/invoicepagetemplates/ClimateControl.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A modern and fresh design for HVAC companies, with cool color accents.',
    useCases: ['AC Repair', 'Maintenance Contracts'],
  },
  {
    id: 'hvac-3',
    name: 'Coolant',
    thumbnailUrl: '/templates/invoicepagetemplates/Coolant.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A simple, grid-based invoice for clear and straightforward HVAC billing.',
    useCases: ['Installations', 'Service Calls'],
  },
  {
    id: 'hvac-4',
    name: 'Corporate Blue',
    thumbnailUrl: '/templates/invoicepagetemplates/CorporateBlue.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A professional and corporate-style invoice for commercial HVAC services.',
    useCases: ['Commercial HVAC', 'Building Maintenance'],
  },
  {
    id: 'hvac-5',
    name: 'Minimal Side',
    thumbnailUrl: '/templates/invoicepagetemplates/Minimalist.png',
    category: 'HVAC Services',
    toolType: 'Invoice',
    description: 'A minimalist design with a side panel for key details, perfect for modern service providers.',
    useCases: ['Smart Thermostats', 'Modern Systems'],
  },
  // --- Roofing Invoice Templates ---
  {
    id: 'roofing-1',
    name: 'Gable',
    thumbnailUrl: '/templates/invoicepagetemplates/Gable.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'A comprehensive template for roofing estimates and invoices.',
    useCases: ['Roofers', 'Exterior Contractors'],
  },
  {
    id: 'roofing-2',
    name: 'Pinnacle',
    thumbnailUrl: '/templates/invoicepagetemplates/Pinnacle.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'A clean, professional template ideal for residential roofing projects.',
    useCases: ['Residential Roofing', 'Shingle Repair'],
  },
  {
    id: 'roofing-3',
    name: 'Ridge',
    thumbnailUrl: '/templates/invoicepagetemplates/Ridge.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'A grid-based, modern template perfect for detailed roofing job breakdowns.',
    useCases: ['Commercial Roofing', 'New Roof Installation'],
  },
  {
    id: 'roofing-4',
    name: 'Shingle',
    thumbnailUrl: '/templates/invoicepagetemplates/Shingle.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'An elegant and clean design for high-end roofing and architectural services.',
    useCases: ['Custom Homes', 'Architectural Roofing'],
  },
  {
    id: 'roofing-5',
    name: 'Ridge Side',
    thumbnailUrl: '/templates/invoicepagetemplates/Ridge.png',
    category: 'Roofing',
    toolType: 'Invoice',
    description: 'A bold, clear template with a side panel for detailed project information.',
    useCases: ['Storm Damage', 'Insurance Claims'],
  },
  {
    id: 'landscaping-1',
    name: 'Green Thumb',
    thumbnailUrl: '/templates/invoicepagetemplates/Green-Thumb.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'A nature-inspired template perfect for landscaping and lawn care businesses.',
    useCases: ['Landscapers', 'Gardeners', 'Arborists'],
  },
  {
    id: 'landscaping-2',
    name: 'Modern & Clean',
    thumbnailUrl: '/templates/invoicepagetemplates/Modern-Clean.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'A clean, professional template for modern landscaping businesses.',
    useCases: ['Design & Build', 'Lawn Maintenance'],
  },
  {
    id: 'landscaping-3',
    name: 'Side Panel',
    thumbnailUrl: '/templates/invoicepagetemplates/Side-Panel.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'Features a green side panel for strong branding and clear information hierarchy.',
    useCases: ['Commercial Landscaping', 'Contracts'],
  },
  {
    id: 'landscaping-4',
    name: 'Elegant',
    thumbnailUrl: '/templates/invoicepagetemplates/Elegant-Lawn.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'A sophisticated design for high-end landscape architecture and garden design.',
    useCases: ['Garden Design', 'High-End Residential'],
  },
  {
    id: 'landscaping-5',
    name: 'Bold & Green',
    thumbnailUrl: '/templates/invoicepagetemplates/Bold-Green.png',
    category: 'Landscaping & Lawn Care',
    toolType: 'Invoice',
    description: 'A bold, grid-based layout that is easy to read and highly organized.',
    useCases: ['Tree Service', 'Large Projects'],
  },
  {
    id: 'cleaning-1',
    name: 'Sparkle',
    thumbnailUrl: '/templates/invoicepagetemplates/Sparkle.png',
    category: 'Cleaning Services',
    toolType: 'Invoice',
    description: 'A bright and clean template for residential and commercial cleaning services.',
    useCases: ['Maid Services', 'Janitorial', 'Carpet Cleaning'],
  },
  {
    id: 'cleaning-2',
    name: 'Fresh',
    thumbnailUrl: '/templates/invoicepagetemplates/Fresh.png',
    category: 'Cleaning Services',
    toolType: 'Invoice',
    description: 'A modern and professional design with clean lines and green accents.',
    useCases: ['Office Cleaning', 'Residential Cleaning'],
  },
  {
    id: 'cleaning-3',
    name: 'Pristine',
    thumbnailUrl: '/templates/invoicepagetemplates/Pristine.png',
    category: 'Cleaning Services',
    toolType: 'Invoice',
    description: 'A minimalist, elegant template for high-end cleaning and specialized services.',
    useCases: ['Deep Cleaning', 'Specialty Services'],
  },
  {
    id: 'auto-repair-1',
    name: 'Mechanic',
    thumbnailUrl: '/templates/invoicepagetemplates/Mechanic.png',
    category: 'Auto Repair',
    toolType: 'Invoice',
    description: 'A practical and detailed template for auto repair shops and mechanics.',
    useCases: ['Auto Shops', 'Body Work', 'Mechanics'],
  },
  {
    id: 'auto-repair-2',
    name: 'Night Shift',
    thumbnailUrl: '/templates/invoicepagetemplates/Night-Shift.png',
    category: 'Auto Repair',
    toolType: 'Invoice',
    description: 'A sleek, dark-themed invoice for modern auto shops and custom garages.',
    useCases: ['Custom Shops', 'Performance Tuning'],
  },
  {
    id: 'auto-repair-3',
    name: 'Classic Garage',
    thumbnailUrl: '/templates/invoicepagetemplates/Classic-Garage.png',
    category: 'Auto Repair',
    toolType: 'Invoice',
    description: 'A vintage-inspired design for classic car restoration and specialty mechanics.',
    useCases: ['Classic Cars', 'Restoration'],
  },
  {
    id: 'it-1',
    name: 'Tech Corporate',
    thumbnailUrl: '/templates/invoicepagetemplates/Tech-Corporate.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A professional and modern template designed for IT services and tech support businesses.',
    useCases: ['IT Support', 'Tech Services', 'Managed Services'],
  },
  {
    id: 'it-2',
    name: 'Modern Dark Mode',
    thumbnailUrl: '/templates/invoicepagetemplates/Modern-Dark-Mode.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A sleek, dark-themed invoice for modern IT consultants and developers.',
    useCases: ['Developers', 'Cybersecurity', 'Consultants'],
  },
  {
    id: 'it-3',
    name: 'Minimalist Grid',
    thumbnailUrl: '/templates/invoicepagetemplates/Minimalist-Grid.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A clean, grid-based layout perfect for itemizing services and billable hours.',
    useCases: ['Web Dev', 'SaaS', 'Freelancers'],
  },
  {
    id: 'it-4',
    name: 'Creative Blue',
    thumbnailUrl: '/templates/invoicepagetemplates/Creative-Blue.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A stylish invoice with a blue side panel, perfect for creative tech agencies.',
    useCases: ['Design Agencies', 'UI/UX Work'],
  },
  {
    id: 'it-5',
    name: 'Startup Vibe',
    thumbnailUrl: '/templates/invoicepagetemplates/Startup-Vibe.png',
    category: 'IT Services / Tech Support',
    toolType: 'Invoice',
    description: 'A modern, minimalist design tailored for startups and agile development projects.',
    useCases: ['Startups', 'App Dev', 'Agile Projects'],
  },
  {
    id: 'freelance-1',
    name: 'Modern Freelancer',
    thumbnailUrl: '/templates/invoicepagetemplates/Modern-Freelancer.png',
    category: 'Freelance / Agency',
    toolType: 'Invoice',
    description: 'A stylish and clean invoice perfect for freelancers, creatives, and small agencies.',
    useCases: ['Freelancers', 'Designers', 'Consultants'],
  },
  {
    id: 'consulting-1',
    name: 'Expert',
    thumbnailUrl: '/templates/invoicepagetemplates/Expert.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A sharp, professional invoice for consultants and advisors.',
    useCases: ['Business Consultants', 'Financial Advisors'],
  },
  {
    id: 'consulting-2',
    name: 'Strategy',
    thumbnailUrl: '/templates/invoicepagetemplates/Strategy.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A modern and clean invoice with a bold header for strategic consultants.',
    useCases: ['Strategy', 'Marketing', 'Management'],
  },
  {
    id: 'consulting-3',
    name: 'Advisory',
    thumbnailUrl: '/templates/invoicepagetemplates/Advisory.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A minimalist and elegant template for advisory services.',
    useCases: ['Financial Advisors', 'Legal Consultants'],
  },
  {
    id: 'consulting-4',
    name: 'Modern',
    thumbnailUrl: '/templates/invoicepagetemplates/ModernConsulting.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A contemporary design with a clean layout and colored header.',
    useCases: ['IT Consulting', 'Tech Advisors'],
  },
  {
    id: 'consulting-5',
    name: 'Minimal',
    thumbnailUrl: '/templates/invoicepagetemplates/MinimalConsulting.png',
    category: 'Consulting',
    toolType: 'Invoice',
    description: 'A simple, text-based invoice perfect for quick and straightforward billing.',
    useCases: ['Coaching', 'Freelance Consulting'],
  },
  {
    id: 'legal-1',
    name: 'Gavel',
    thumbnailUrl: '/templates/invoicepagetemplates/Gavel.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'A formal and classic invoice template suitable for law firms and legal professionals.',
    useCases: ['Lawyers', 'Paralegals', 'Legal Advisors'],
  },
  {
    id: 'legal-2',
    name: 'Advocate',
    thumbnailUrl: '/templates/invoicepagetemplates/Advocate.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'A strong, modern invoice with a bold header, perfect for legal practices.',
    useCases: ['Attorneys', 'Law Firms'],
  },
  {
    id: 'legal-3',
    name: 'Justice',
    thumbnailUrl: '/templates/invoicepagetemplates/Justice.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'A clean, grid-based template for clear and detailed legal billing.',
    useCases: ['Legal Billing', 'Case Files'],
  },
  {
    id: 'legal-4',
    name: 'Paralegal',
    thumbnailUrl: '/templates/invoicepagetemplates/Paralegal.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'An elegant and formal template with a classic serif font.',
    useCases: ['Paralegal Services', 'Document Review'],
  },
  {
    id: 'legal-5',
    name: 'The Firm',
    thumbnailUrl: '/templates/invoicepagetemplates/The-Firm.png',
    category: 'Legal Services',
    toolType: 'Invoice',
    description: 'A corporate-style invoice with a colored side panel for a professional look.',
    useCases: ['Corporate Law', 'Retainers'],
  },
  {
    id: 'medical-1',
    name: 'Caduceus',
    thumbnailUrl: '/templates/invoicepagetemplates/Caduceus.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A clean and professional template for medical billing and healthcare services.',
    useCases: ['Clinics', 'Doctors', 'Medical Billing'],
  },
  {
    id: 'medical-2',
    name: 'Vitality',
    thumbnailUrl: '/templates/invoicepagetemplates/Vitality.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A simple and clean template for medical practitioners and clinics.',
    useCases: ['Private Practice', 'Specialists'],
  },
  {
    id: 'medical-3',
    name: 'Clinic',
    thumbnailUrl: '/templates/invoicepagetemplates/Clinic.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A professional design with a side panel for organizing patient and billing info.',
    useCases: ['Hospitals', 'Clinics'],
  },
  {
    id: 'medical-4',
    name: 'Wellness',
    thumbnailUrl: '/templates/invoicepagetemplates/Wellness.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A modern and calming design for wellness centers and holistic practices.',
    useCases: ['Wellness Centers', 'Therapists'],
  },
  {
    id: 'medical-5',
    name: 'Remedy',
    thumbnailUrl: '/templates/invoicepagetemplates/Remedy.png',
    category: 'Medical / Healthcare',
    toolType: 'Invoice',
    description: 'A classic, formal template for detailed medical statements and billing.',
    useCases: ['Medical Statements', 'Insurance Billing'],
  },
  {
    id: 'ecommerce-1',
    name: 'Shopify',
    thumbnailUrl: '/templates/invoicepagetemplates/Shopify.png',
    category: 'E-commerce / Online Store',
    toolType: 'Invoice',
    description: 'A modern and item-focused invoice for e-commerce and online sales.',
    useCases: ['Online Stores', 'E-commerce', 'Dropshippers'],
  },
  {
    id: 'retail-1',
    name: 'Receipt',
    thumbnailUrl: '/templates/invoicepagetemplates/Receipt.png',
    category: 'Retail / Wholesale',
    toolType: 'Invoice',
    description: 'A clear, receipt-style invoice for retail sales and wholesale orders.',
    useCases: ['Retail Stores', 'Wholesalers'],
  },
  {
    id: 'photography-1',
    name: 'Lens',
    thumbnailUrl: '/templates/invoicepagetemplates/Lens.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'An elegant template with a focus on visual branding for photographers.',
    useCases: ['Photographers', 'Videographers'],
  },
  {
    id: 'photography-2',
    name: 'Shutter',
    thumbnailUrl: '/templates/invoicepagetemplates/Shutter.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'A bold, modern design with a dark header for a strong visual impact.',
    useCases: ['Event Photography', 'Portraits'],
  },
  {
    id: 'photography-3',
    name: 'Aperture',
    thumbnailUrl: '/templates/invoicepagetemplates/Aperture.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'A clean, minimalist template that puts the focus on the services rendered.',
    useCases: ['Wedding Photography', 'Product Shoots'],
  },
  {
    id: 'photography-4',
    name: 'Golden Hour',
    thumbnailUrl: '/templates/invoicepagetemplates/Golden-Hour.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'A warm, inviting template with a colored header, perfect for lifestyle photographers.',
    useCases: ['Lifestyle', 'Family Portraits'],
  },
  {
    id: 'photography-5',
    name: 'Portfolio',
    thumbnailUrl: '/templates/invoicepagetemplates/Portfolio.png',
    category: 'Photography',
    toolType: 'Invoice',
    description: 'A minimalist design with a side accent, ideal for showcasing professional photography services.',
    useCases: ['Commercial', 'Fashion'],
  },
  {
    id: 'real-estate-1',
    name: 'Property',
    thumbnailUrl: '/templates/invoicepagetemplates/Property.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'A professional template for real estate transactions and property management fees.',
    useCases: ['Realtors', 'Property Managers'],
  },
  {
    id: 'real-estate-2',
    name: 'Listing',
    thumbnailUrl: '/templates/invoicepagetemplates/Listing.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'A clean, grid-based invoice for real estate services and commissions.',
    useCases: ['Real Estate Agents', 'Brokerages'],
  },
  {
    id: 'real-estate-3',
    name: 'Homestead',
    thumbnailUrl: '/templates/invoicepagetemplates/Homestead.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'An elegant, classic design suitable for property sales and legal documentation.',
    useCases: ['Property Sales', 'Legal'],
  },
  {
    id: 'real-estate-4',
    name: 'Agency',
    thumbnailUrl: '/templates/invoicepagetemplates/Agency.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'A modern template with a side panel for a strong brand presence.',
    useCases: ['Real Estate Agencies', 'Leasing'],
  },
  {
    id: 'real-estate-5',
    name: 'Manor',
    thumbnailUrl: '/templates/invoicepagetemplates/Manor.png',
    category: 'Real Estate / Property Management',
    toolType: 'Invoice',
    description: 'A warm, inviting template perfect for residential property management.',
    useCases: ['Property Management', 'HOA'],
  },
  {
    id: 'transportation-1',
    name: 'Freight',
    thumbnailUrl: '/templates/invoicepagetemplates/Freight.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A clear and detailed invoice for transportation and logistics companies.',
    useCases: ['Logistics', 'Freight', 'Trucking'],
  },
  {
    id: 'transportation-2',
    name: 'Logistics',
    thumbnailUrl: '/templates/invoicepagetemplates/Logistics.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A clean, professional template for logistics and shipping services.',
    useCases: ['Shipping', 'Freight Forwarding'],
  },
  {
    id: 'transportation-3',
    name: 'Haul',
    thumbnailUrl: '/templates/invoicepagetemplates/Haul.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A bold, modern design perfect for trucking and hauling companies.',
    useCases: ['Trucking', 'Hauling'],
  },
  {
    id: 'transportation-4',
    name: 'Dispatch',
    thumbnailUrl: '/templates/invoicepagetemplates/Dispatch.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A sleek, dark-themed invoice for modern logistics and dispatch services.',
    useCases: ['Dispatch Services', 'Fleet Management'],
  },
  {
    id: 'transportation-5',
    name: 'Cargo',
    thumbnailUrl: '/templates/invoicepagetemplates/Cargo.png',
    category: 'Transportation / Trucking',
    toolType: 'Invoice',
    description: 'A classic, serif-font template for formal shipping and cargo documentation.',
    useCases: ['Cargo Shipping', 'Import/Export'],
  },
  {
    id: 'rental-1',
    name: 'Lease',
    thumbnailUrl: '/templates/invoicepagetemplates/Lease.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A simple invoice for rental properties and equipment.',
    useCases: ['Landlords', 'Equipment Rental'],
  },
  {
    id: 'rental-2',
    name: 'Booking',
    thumbnailUrl: '/templates/invoicepagetemplates/Booking.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A clean and simple invoice for rental bookings and services.',
    useCases: ['Vacation Rentals', 'Car Rentals'],
  },
  {
    id: 'rental-3',
    name: 'Agreement',
    thumbnailUrl: '/templates/invoicepagetemplates/Agreement.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A formal, classic template for rental agreements and long-term leases.',
    useCases: ['Property Leasing', 'Long-term Rentals'],
  },
  {
    id: 'rental-4',
    name: 'Reservation',
    thumbnailUrl: '/templates/invoicepagetemplates/Reservation.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A modern template with a side panel, great for reservation systems.',
    useCases: ['Event Rentals', 'Reservations'],
  },
  {
    id: 'rental-5',
    name: 'Manor Rental',
    thumbnailUrl: '/templates/invoicepagetemplates/Manor-Rental.png',
    category: 'Rental / Property',
    toolType: 'Invoice',
    description: 'A warm, inviting template for residential rentals and property management.',
    useCases: ['Apartment Rentals', 'Real Estate'],
  },

  // --- ESTIMATE & QUOTE TEMPLATES ---
  {
    id: 'generic-1',
    name: 'Classic Estimate',
    thumbnailUrl: '/templates/generic-1.png',
    category: 'Generic',
    toolType: 'Estimate',
    description: 'A timeless and professional estimate layout suitable for any industry. Clear, organized, and easy for clients to understand.',
    useCases: ['Any Business', 'General Quotes', 'Proposals'],
  },
  {
    id: 'generic-2',
    name: 'Modern Estimate',
    thumbnailUrl: '/templates/generic-2.png',
    category: 'Generic',
    toolType: 'Estimate',
    description: 'A sleek, contemporary design that puts your brand front and center. Ideal for modern businesses and creative professionals.',
    useCases: ['Agencies', 'Tech Startups', 'Consultants'],
  },
  {
    id: 'generic-1',
    name: 'Classic Quote',
    thumbnailUrl: '/templates/generic-1.png',
    category: 'Generic',
    toolType: 'Quote',
    description: 'A timeless and professional quote layout suitable for any industry. Clear, organized, and easy for clients to understand.',
    useCases: ['Any Business', 'General Quotes', 'Proposals'],
  },
  {
    id: 'generic-2',
    name: 'Modern Quote',
    thumbnailUrl: '/templates/generic-2.png',
    category: 'Generic',
    toolType: 'Quote',
    description: 'A sleek, contemporary design that puts your brand front and center. Ideal for modern businesses and creative professionals.',
    useCases: ['Agencies', 'Tech Startups', 'Consultants'],
  },
  {
    id: 'construction-1',
    name: 'Foundation Estimate',
    thumbnailUrl: '/templates/construction-1.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A detailed estimate template for construction work.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-2',
    name: 'Modern Dark Estimate',
    thumbnailUrl: '/templates/construction-2.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A dark, modern estimate for construction projects.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-3',
    name: 'Minimalist Estimate',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanMinimal.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A clean, minimal estimate for construction services.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-4',
    name: 'Side Accent Estimate',
    thumbnailUrl: '/templates/invoicepagetemplates/SideAccent.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A construction estimate with a colored side accent panel.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },
  {
    id: 'construction-5',
    name: 'Bold Grid Estimate',
    thumbnailUrl: '/templates/invoicepagetemplates/CleanGrid.png',
    category: 'Construction Estimate',
    toolType: 'Estimate',
    description: 'A grid-based layout for clear construction estimates.',
    useCases: ['Construction', 'Building', 'Contracting'],
  },

  // --- INSURANCE TEMPLATES ---
  {
    id: 'usa-claim-default',
    name: 'USA Claim Form',
    thumbnailUrl: '/templates/Usa-insurance.png',
    category: 'Claims',
    toolType: 'Insurance',
    description: 'A standard, comprehensive claim form template suitable for various insurance types in the USA.',
    useCases: ['Claims Processing', 'Damage Reports', 'Vehicle Insurance'],
  },
  {
    id: 'usa-service',
    name: 'USA Service',
    thumbnailUrl: '/templates/Usa-service.png',
    category: 'Policy',
    toolType: 'Insurance',
    description: 'A professional template for outlining insurance policy details, coverage, and terms for US-based clients.',
    useCases: ['Policy Issuance', 'Coverage Summary', 'Certificates'],
  },
];